version: '3.8'
services:
  ros:
    image: ros:noetic-ros-base
    container_name: ros-noetic
    volumes:
      - ./ros_ws/:/ros_ws
    environment:
      - ROS_IP = localhost
      - ROS_MASTER_URI = localhost:11311
    command: "tail -f /dev/null"